### PR TITLE
Add exception when trying to load a partial snapshot with partial loading

### PR DESCRIPTION
**Pull request by JBorrow**
"Fixes" #169 by notifying the user if they are trying to do something naughty.

@Joeybraspenning can you try this branch out and let me know if it crashes with your old use case?

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
@Joeybraspenning this should fix the issue you reported. Or at least tell you there is an error.

**Comment by Joeybraspenning** [comment]
Ah sorry, missed this, will try within 24h

**Comment by MatthieuSchaller** [comment]
@Joeybraspenning any updates?

**Comment by JBorrow** [comment]
@Joeybraspenning a reminder we're waiting for you to test this before we can merge

**Comment by Joeybraspenning** [comment]
Having a look now, github is connected to my personal email which I tend to ignore, sorry about that

**Comment by Joeybraspenning** [comment]
Seems all good now, I get an error telling me I can't create masks on partial snapshots:

```
swiftsimio.objects.InvalidSnapshot: InvalidSnapshot: You cannot use masks on partial snapshots. Please use the virtual file generated by SWIFT (use snapshot.hdf5, not snapshot.0.hdf5).
```

That's sufficient for me, prevents me from ever making this mistake by accident

**Pull request merged**
