### PR TITLE
Import smoothing_length_generation is as part of swiftsimio.visualisation

### PR DESCRIPTION
**Pull request by bwvdnbro**
Addresses #74.

### CODE REVIEW

**Comment by JBorrow** [comment]
This doesn't make much sense to me

**Comment by JBorrow** [comment]
If we're going to do this, we might as well just

`from .smoothing_length_generation import generate_smoothing_lengths`, and make it a top-level function.

**Comment by bwvdnbro** [comment]
Works for me too. I agree with @Fonotec that you should be able to access all the functionality with one import.

**Comment by bwvdnbro** [comment]
I have implemented your suggestion.

**Pull request merged**
