### PR TITLE
Return cosmo_array from smoothing length calculation for non-gas particles

### LINKED ISSUE #143: Smoothing length calculation for non-gas particles returns `unyt_array`
Some recent changes to the visualisation module check that the smoothing lengths and coordinates have compatible attributes (e.g. both comoving, or both physical). However, `visualisation.smoothing_length_generation.generate_smoothing_lengths` returns a `unyt_array`, so these checks always fail with an `AttributeError` and the smoothing lengths are unusable.

Putting together a PR for this, it includes a test that currently fails:

```
@requires("cosmological_volume.hdf5")
def test_nongas_smoothing_lengths(filename):
    """
    Test that the visualisation tools to calculate smoothing lengths give usable results.
    """

    data = load(filename)
    data.dark_matter.smoothing_length = generate_smoothing_lengths(
        data.dark_matter.coordinates, data.metadata.boxsize, kernel_gamma=1.8
    )
    project_pixel_grid(
        data.dark_matter,
        boxsize=data.metadata.boxsize,
        resolution=256,
        project="masses",
    )

    # if project_pixel_grid runs without error the smoothing lengths seem usable
    return
```

### PR DESCRIPTION
**Pull request by kyleaoman**
Resolves #143

### CODE REVIEW

**Comment by JBorrow** [comment]
This function is used in a lot of external code so I'm concerned about introducing breaking changes (in particular requiring cosmo array). I currently use this with Arepo data and a base unyt array in some scripts. Can we give the cosmo array sensible defaults?

**Comment by kyleaoman** [comment]
Would we be happy returning a cosmo_array for cosmo_array input, and a unyt_array for unyt_array input? That should be simple to implement, and give intuitive results?

**Comment by JBorrow** [comment]
Yeah that makes sense to do.

**Comment by kyleaoman** [comment]
Great, all done.

**Pull request merged**
