### PR TITLE
Added support for non-square projections.

### PR DESCRIPTION
**Pull request by bwvdnbro**
Should be the equivalent of #116, but then for the projection function.

### CODE REVIEW

**Comment by bwvdnbro** [comment]
The CI failures seem to be unrelated to this pull request.

**Comment by JBorrow** [comment]
@kyleaoman failures seem to be due to new imports from unyt, can you check that out?

**Comment by JBorrow** [comment]
Your changes look good to me @bwvdnbro

**Comment by kyleaoman** [comment]
> @kyleaoman failures seem to be due to new imports from unyt, can you check that out?

Yup, there's a PR for this #145. No technical hurdles on that one, but need a bit of input on backwards compatibility and possibly to drop support for python3.6 (which unyt no longer supports) before merging.

**Pull request merged**
